### PR TITLE
Fix save&read serializable message

### PR DESCRIPTION
**Pull request by 3064709**
In my DB saving column 'swift_message' like this  O:24:"nterms\mailqueue\Message":3:{s:38:"

### CODE REVIEW

**Comment by nterms** [comment]
Hi @3064709, could you please explain bit more about your issues and what you are trying to solve here?

**Comment by rochdi80tn** [comment]
Hi @3064709,
Did you face a problem with serialzed data not being base64 encoded ?

**Comment by 3064709** [comment]
@rochdi80tn Yes, serialize make not valid string

**Comment by 3064709** [comment]
I have error like this https://davidwalsh.name/php-serialize-unserialize-issues

**Comment by rochdi80tn** [comment]
Sounds good to me.

**Comment by nterms** [comment]
Sounds good, thanks for the PR

**Pull request merged**
